// Generated by CoffeeScript 1.3.3

/*
# Router Section
*/


(function() {

  io.sockets.on("connection", function(socket) {
    socket.emit("connection down", socket.id);
    socket.on("backbone event up", function(data) {
      var content, eventname;
      if (data == null) {
        data = {};
      }
      eventname = data['eventname'];
      content = _.extend(data, {
        "local": true
      });
      console.log("========================");
      console.log("------------------------");
      return Backbone.Events.trigger(eventname, content);
    });
    return Backbone.Events.on("all", function(eventname) {
      var rest;
      rest = Array.prototype.slice.call(arguments, 1);
      console.log("=======================");
      console.log("Backbone Event " + eventname + " Up Detected!!!");
      return console.log(JSON.stringify(rest[0]));
    });
  });

}).call(this);
