// Generated by CoffeeScript 1.3.3

/*
# Initializers Live Here
*/


(function() {
  var Backbone, Card, Cards, Room, Rooms, io, port, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  port = 3123;

  io = require("socket.io").listen(port);

  Backbone = require("backbone");

  _ = require("underscore");

  Card = (function(_super) {

    __extends(Card, _super);

    function Card() {
      return Card.__super__.constructor.apply(this, arguments);
    }

    Card.prototype.defaults = {
      content: "",
      category: "white",
      image: null
    };

    return Card;

  })(Backbone.Model);

  Cards = (function(_super) {

    __extends(Cards, _super);

    function Cards() {
      return Cards.__super__.constructor.apply(this, arguments);
    }

    Cards.prototype.model = Card;

    Cards.retrieve = function(options) {
      switch (options["category"]) {
        case "black":
          return [
            new Card({
              "category": "black",
              "content": "some content here"
            })
          ];
        case "white":
          return [
            new Card({
              "category": "white",
              "content": "niggers"
            })
          ];
      }
    };

    return Cards;

  })(Backbone.Collection);

  Room = (function(_super) {

    __extends(Room, _super);

    function Room() {
      return Room.__super__.constructor.apply(this, arguments);
    }

    Room.white_card_time = 15000;

    Room.vote_time = 15000;

    Room.starting_hand = 10;

    Room.prototype.defaults = {
      state: "pre-game",
      name: "default",
      start_vote: function() {
        throw "Not Implemented Error";
      },
      announce_winner: function() {
        throw "Not Implemented Error";
      },
      pass_whites: function() {
        throw "Not Implemented Error";
      },
      pass_blacks: function() {
        throw "Not Implemented Error";
      }
    };

    Room.prototype.initialize = function() {
      return this.counter = 0;
    };

    Room.prototype.join = function(data) {
      if (data == null) {
        data = {};
      }
      if (this.counter === 0) {
        this.start_game();
      }
      this.counter += 1;
      return _.extend(data, {
        cards: Cards.retrieve({
          limit: Room.starting_hand,
          category: "white"
        })
      });
    };

    Room.prototype.start_game = function() {
      var black, white;
      this.set("state", "black-card", {
        silent: true
      });
      white = Cards.retrieve({
        limit: this.counter,
        category: "white"
      });
      this.get("pass_whites")(white);
      black = Cards.retrieve({
        limit: 1,
        category: "black"
      });
      return this.get("pass_blacks")(black);
    };

    Room.prototype.leave = function(data) {
      this.counter -= 1;
      if (this.counter === 0) {
        if (this.white_timer != null) {
          clearTimeout(this.white_timer);
        }
        if (this.vote_timer != null) {
          clearTimeout(this.vote_timer);
        }
        if (this.post_game_timer != null) {
          clearTimeout(this.post_game_timer);
        }
        this.destroy();
      }
      return data;
    };

    Room.prototype.white_card = function(data) {
      var _this = this;
      switch (this.get("state")) {
        case "black-card":
          this.white_timer = setTimeout((function() {
            return _this.start_vote();
          }), Room.white_card_time);
          this.set("state", "white-card", {
            silent: true
          });
          return data;
        case "white-card":
          return data;
        default:
          return null;
      }
    };

    Room.prototype.start_vote = function() {
      this.set("state", "vote", {
        silent: true
      });
      return this.get("start_vote")();
    };

    Room.prototype.vote = function(data) {
      var _this = this;
      switch (this.get("state")) {
        case "vote":
          this.vote_timer = setTimeout((function() {
            return _this.announce_winner();
          }), Room.vote_time);
          this.set("state", "vote-counting", {
            silent: true
          });
          return data;
        case "vote-counting":
          return data;
        default:
          return null;
      }
    };

    Room.prototype.announce_winner = function() {
      var _this = this;
      this.set("state", "post-game", {
        silent: true
      });
      this.get("announce_winner")();
      return this.post_game_timer = setTimeout((function() {
        return _this.start_game();
      }), 2000);
    };

    return Room;

  })(Backbone.Model);

  Rooms = (function(_super) {

    __extends(Rooms, _super);

    function Rooms() {
      return Rooms.__super__.constructor.apply(this, arguments);
    }

    Rooms.prototype.names = {};

    Rooms.prototype.retrieve = function(name) {
      var position, room;
      position = this.names[name];
      if (position != null) {
        return this.at(position);
      } else {
        this.names[name] = this.length;
        room = new Room({
          "name": name,
          start_vote: function(data) {
            return io.sockets["in"](name).emit("start vote down", data);
          },
          announce_winner: function(data) {
            return io.sockets["in"](name).emit("winner down", data);
          },
          pass_whites: function(data) {
            return io.sockets["in"](name).emit("white cards down", data);
          },
          pass_blacks: function(data) {
            return io.sockets["in"](name).emit("black card down", data);
          }
        });
        return this.add();
      }
    };

    Rooms.prototype.model = Room;

    return Rooms;

  })(Backbone.Collection);

  /*
  # Router Section
  */


  io.sockets.on("connection", function(socket) {
    socket.on("join room up", function(data) {
      var player, room;
      room = Rooms.retrieve(data['roomid']);
      player = room.join(data);
      socket.join(data['roomid']);
      return socket.to(data['roomid']).emit("join room down", player);
    });
    socket.on("white card up", function(data) {
      var room, white_card;
      room = Rooms.retrieve(data['roomid']);
      white_card = room.white_card(data);
      if (white_card != null) {
        return socket.to(data['roomid']).emit("white card down", white_card);
      }
    });
    socket.on("vote up", function(data) {
      var room, vote;
      room = Rooms.retrieve(data['roomid']);
      vote = room.vote(data);
      if (vote != null) {
        return socket.to(data['roomid']).emit("vote down", vote);
      }
    });
    return socket.on("leave room up", function(data) {
      var player, room;
      room = Rooms.retrieve(data['roomid']);
      player = room.leave(data);
      if (player != null) {
        return socket.to(data['roomid']).emit("leave room down", player);
      }
    });
  });

}).call(this);
