// Generated by CoffeeScript 1.3.3

/*
# Room "Model" Spec
*/


(function() {

  describe("Room Model", function() {
    describe("Sanity Test", function() {
      return it("should not be null", function() {
        return expect(Room).to.be.ok;
      });
    });
    return describe("initialization", function() {
      beforeEach(function() {
        return this.room = new Room({
          "name": "test room",
          "start_vote": function() {
            return false;
          },
          "announce_winner": function() {
            return false;
          },
          "pass_whites": function(whites) {
            return false;
          },
          "pass_blacks": function(blacks) {
            return false;
          }
        });
      });
      afterEach(function() {
        return this.room.destroy();
      });
      it("should work", function() {
        return expect(this.room.get("name")).to.equal("test room");
      });
      it("should have 0 counter", function() {
        return expect(this.room.counter).to.equal(0);
      });
      return it("should attempt to join a new game", function() {
        this.room.join();
        return expect(this.room.counter).to.equal(1);
      });
    });
  });

}).call(this);
