// Generated by CoffeeScript 1.3.3
(function() {
  var Cards,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Cards = (function(_super) {

    __extends(Cards, _super);

    function Cards() {
      return Cards.__super__.constructor.apply(this, arguments);
    }

    Cards.prototype.model = Card;

    Cards.retrieve = function(options) {
      switch (options["category"]) {
        case "black":
          return [
            new Card({
              "category": "black",
              "content": "some content here"
            })
          ];
        case "white":
          return [
            new Card({
              "category": "white",
              "content": "niggers"
            })
          ];
      }
    };

    return Cards;

  })(Backbone.Collection);

}).call(this);
