// Generated by CoffeeScript 1.3.3
(function() {
  var Rooms,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Rooms = (function(_super) {

    __extends(Rooms, _super);

    function Rooms() {
      return Rooms.__super__.constructor.apply(this, arguments);
    }

    Rooms.prototype.names = {};

    Rooms.prototype.retrieve = function(name) {
      var position, room;
      position = this.names[name];
      if (position != null) {
        return this.at(position);
      } else {
        this.names[name] = this.length;
        room = new Room({
          "name": name
        });
        return this.add(room);
      }
    };

    Rooms.prototype.model = Room;

    return Rooms;

  })(Backbone.Collection);

}).call(this);
