// Generated by CoffeeScript 1.3.3
(function() {
  var assert, chai, expect, should;

  chai = require("chai");

  expect = chai.expect;

  should = chai.should();

  assert = chai.assert;

}).call(this);
