// Generated by CoffeeScript 1.3.3

/*
# Tests for Card collections
*/


(function() {

  describe("Cards", function() {
    describe("Sanity test", function() {
      return it("should exist", function() {
        return expect(Cards).to.be.ok;
      });
    });
    return describe("Retrieve", function() {
      return it("should retrieve cards", function() {
        var cards;
        cards = Cards.retrieve({
          category: "black",
          limit: 1
        });
        return expect(cards.length).to.equal(1);
      });
    });
  });

}).call(this);
