// Generated by CoffeeScript 1.3.3
(function() {

  describe("Rooms Collection", function() {
    describe("Sanity Test", function() {
      return it("should not be null", function() {
        return expect(Rooms).to.be.ok;
      });
    });
    return describe("rooms", function() {
      var rooms;
      rooms = new Rooms();
      it("should create a collection", function() {
        expect(rooms).to.be.ok;
        return expect(rooms.length).to.equal(0);
      });
      return it("should create a room", function() {
        rooms.retrieve("test room");
        return expect(rooms.length).to.equal(1);
      });
    });
  });

}).call(this);
